spring:
  application:
    name: config-repo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dhnnjydahiya/jiralite-configs
          default-label: main
          clone-on-start: true
          search-paths: '{application}'
server:
  port: 8888
